export const allCars = [
  {
    city_mpg: 23,
    class: 'compact car',
    combination_mpg: 25,
    cylinders: 4,
    displacement: 2,
    drive: 'awd',
    fuel_type: 'gas',
    highway_mpg: 30,
    make: 'volkswagen',
    model: 'golf r',
    transmission: 'a',
    year: 2016
  },
  {
    city_mpg: 22,
    class: 'compact car',
    combination_mpg: 25,
    cylinders: 4,
    displacement: 2,
    drive: 'awd',
    fuel_type: 'gas',
    highway_mpg: 31,
    make: 'volkswagen',
    model: 'golf r',
    transmission: 'm',
    year: 2016
  },
  {
    city_mpg: 22,
    class: 'subcompact car',
    combination_mpg: 25,
    cylinders: 4,
    displacement: 2,
    drive: 'fwd',
    fuel_type: 'gas',
    highway_mpg: 30,
    make: 'volkswagen',
    model: 'eos',
    transmission: 'a',
    year: 2016
  },
  {
    city_mpg: 25,
    class: 'compact car',
    combination_mpg: 28,
    cylinders: 4,
    displacement: 2,
    drive: 'fwd',
    fuel_type: 'gas',
    highway_mpg: 33,
    make: 'volkswagen',
    model: 'gti',
    transmission: 'a',
    year: 2016
  },
  {
    city_mpg: 25,
    class: 'compact car',
    combination_mpg: 28,
    cylinders: 4,
    displacement: 2,
    drive: 'fwd',
    fuel_type: 'gas',
    highway_mpg: 34,
    make: 'volkswagen',
    model: 'gti',
    transmission: 'm',
    year: 2016
  },
  {
    city_mpg: 25,
    class: 'compact car',
    combination_mpg: 29,
    cylinders: 4,
    displacement: 1.8,
    drive: 'fwd',
    fuel_type: 'gas',
    highway_mpg: 35,
    make: 'volkswagen',
    model: 'golf',
    transmission: 'a',
    year: 2016
  },
  {
    city_mpg: 25,
    class: 'compact car',
    combination_mpg: 29,
    cylinders: 4,
    displacement: 1.8,
    drive: 'fwd',
    fuel_type: 'gas',
    highway_mpg: 36,
    make: 'volkswagen',
    model: 'golf',
    transmission: 'm',
    year: 2016
  },
  {
    city_mpg: 22,
    class: 'compact car',
    combination_mpg: 25,
    cylinders: 4,
    displacement: 2,
    drive: 'fwd',
    fuel_type: 'gas',
    highway_mpg: 31,
    make: 'volkswagen',
    model: 'cc',
    transmission: 'a',
    year: 2016
  },
  {
    city_mpg: 22,
    class: 'compact car',
    combination_mpg: 25,
    cylinders: 4,
    displacement: 2,
    drive: 'fwd',
    fuel_type: 'gas',
    highway_mpg: 31,
    make: 'volkswagen',
    model: 'cc',
    transmission: 'a',
    year: 2016
  }
  ,
  {
    city_mpg: 22,
    class: 'compact car',
    combination_mpg: 25,
    cylinders: 4,
    displacement: 2,
    drive: 'fwd',
    fuel_type: 'gas',
    highway_mpg: 31,
    make: 'volkswagen',
    model: 'cc',
    transmission: 'a',
    year: 2016
  },
  {
    city_mpg: 22,
    class: 'compact car',
    combination_mpg: 25,
    cylinders: 4,
    displacement: 2,
    drive: 'fwd',
    fuel_type: 'gas',
    highway_mpg: 31,
    make: 'volkswagen',
    model: 'cc',
    transmission: 'a',
    year: 2016
  },
  {
    city_mpg: 22,
    class: 'compact car',
    combination_mpg: 25,
    cylinders: 4,
    displacement: 2,
    drive: 'fwd',
    fuel_type: 'gas',
    highway_mpg: 31,
    make: 'volkswagen',
    model: 'cc',
    transmission: 'a',
    year: 2016
  }, {
    city_mpg: 23,
    class: 'compact car',
    combination_mpg: 25,
    cylinders: 4,
    displacement: 2,
    drive: 'awd',
    fuel_type: 'gas',
    highway_mpg: 30,
    make: 'volkswagen',
    model: 'golf r',
    transmission: 'a',
    year: 2016
  },
  {
    city_mpg: 22,
    class: 'compact car',
    combination_mpg: 25,
    cylinders: 4,
    displacement: 2,
    drive: 'awd',
    fuel_type: 'gas',
    highway_mpg: 31,
    make: 'volkswagen',
    model: 'golf r',
    transmission: 'm',
    year: 2016
  },
  {
    city_mpg: 22,
    class: 'subcompact car',
    combination_mpg: 25,
    cylinders: 4,
    displacement: 2,
    drive: 'fwd',
    fuel_type: 'gas',
    highway_mpg: 30,
    make: 'volkswagen',
    model: 'eos',
    transmission: 'a',
    year: 2016
  },
  {
    city_mpg: 25,
    class: 'compact car',
    combination_mpg: 28,
    cylinders: 4,
    displacement: 2,
    drive: 'fwd',
    fuel_type: 'gas',
    highway_mpg: 33,
    make: 'volkswagen',
    model: 'gti',
    transmission: 'a',
    year: 2016
  }, {
    city_mpg: 23,
    class: 'compact car',
    combination_mpg: 25,
    cylinders: 4,
    displacement: 2,
    drive: 'awd',
    fuel_type: 'gas',
    highway_mpg: 30,
    make: 'volkswagen',
    model: 'golf r',
    transmission: 'a',
    year: 2016
  },
  {
    city_mpg: 22,
    class: 'compact car',
    combination_mpg: 25,
    cylinders: 4,
    displacement: 2,
    drive: 'awd',
    fuel_type: 'gas',
    highway_mpg: 31,
    make: 'volkswagen',
    model: 'golf r',
    transmission: 'm',
    year: 2016
  },
  {
    city_mpg: 22,
    class: 'subcompact car',
    combination_mpg: 25,
    cylinders: 4,
    displacement: 2,
    drive: 'fwd',
    fuel_type: 'gas',
    highway_mpg: 30,
    make: 'volkswagen',
    model: 'eos',
    transmission: 'a',
    year: 2016
  },
  {
    city_mpg: 25,
    class: 'compact car',
    combination_mpg: 28,
    cylinders: 4,
    displacement: 2,
    drive: 'fwd',
    fuel_type: 'gas',
    highway_mpg: 33,
    make: 'volkswagen',
    model: 'gti',
    transmission: 'a',
    year: 2016
  }, {
    city_mpg: 23,
    class: 'compact car',
    combination_mpg: 25,
    cylinders: 4,
    displacement: 2,
    drive: 'awd',
    fuel_type: 'gas',
    highway_mpg: 30,
    make: 'volkswagen',
    model: 'golf r',
    transmission: 'a',
    year: 2016
  },
  {
    city_mpg: 22,
    class: 'compact car',
    combination_mpg: 25,
    cylinders: 4,
    displacement: 2,
    drive: 'awd',
    fuel_type: 'gas',
    highway_mpg: 31,
    make: 'volkswagen',
    model: 'golf r',
    transmission: 'm',
    year: 2016
  },
  {
    city_mpg: 22,
    class: 'subcompact car',
    combination_mpg: 25,
    cylinders: 4,
    displacement: 2,
    drive: 'fwd',
    fuel_type: 'gas',
    highway_mpg: 30,
    make: 'volkswagen',
    model: 'eos',
    transmission: 'a',
    year: 2016
  },
  {
    city_mpg: 25,
    class: 'compact car',
    combination_mpg: 28,
    cylinders: 4,
    displacement: 2,
    drive: 'fwd',
    fuel_type: 'gas',
    highway_mpg: 33,
    make: 'volkswagen',
    model: 'gti',
    transmission: 'a',
    year: 2016
  }
]